version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiportal-front
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    environment:
      - VITE_PORT=${VITE_PORT}
      - VITE_APP_AUTH=${VITE_APP_AUTH}
      - VITE_APP_STRAPI_URL=${VITE_APP_STRAPI_URL}
      - VITE_APP_STRAPI_URL_IMGS=${VITE_APP_STRAPI_URL_IMGS}
      - VITE_APP_STRAPI_KONG_API_KEY=${VITE_APP_STRAPI_KONG_API_KEY}
      - VITE_APP_KEYCLOAK_CLIENT_ID=${VITE_APP_KEYCLOAK_CLIENT_ID}
      - VITE_SITE_KEY_RECAPTCHA=${VITE_SITE_KEY_RECAPTCHA}
      - VITE_APP_HOME_PAGE_SLUG=${VITE_APP_HOME_PAGE_SLUG}
      - VITE_APP_MCPS_PAGE_SLUG=${VITE_APP_MCPS_PAGE_SLUG}
      - VITE_APP_APIS_PAGE_SLUG=${VITE_APP_APIS_PAGE_SLUG}
      - VITE_APP_BLOG_PAGE_SLUG=${VITE_APP_BLOG_PAGE_SLUG}
      - VITE_APP_FAQ_PAGE_SLUG=${VITE_APP_FAQ_PAGE_SLUG}
      - VITE_APP_TERMS_PAGE_SLUG=${VITE_APP_TERMS_PAGE_SLUG}
      - VITE_APP_POLICY_PAGE_SLUG=${VITE_APP_POLICY_PAGE_SLUG}
    networks:
      - apimarket-net

networks:
  apimarket-net:
    driver: bridge