import React from 'react';
import Accordion from '../components/Accordion/Accordion';
import BannerStatic from '../components/Banner/BannerStatic';

function Faqs(props) {
  const faqs = [
    { title: 'Información', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.' },
    { title: 'dicta dolor suscipit', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.' },
    { title: 'dicta dolor suscipit', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.' },
    { title: 'dicta dolor suscipit', body: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur hic amet blanditiis cumque accusamus maxime beatae dolorem placeat, quae illum facere nostrum quam, eum porro dolor veniam. Est accusantium maxime, mollitia voluptate rerum ut voluptatum. Minus quas nam repellendus rem. Nam officiis corporis ipsa? Rerum, omnis? Quos quod odio itaque.' },
  ];
  return (
    <div>
      <BannerStatic
        title='Preguntas frecuentes'
        img='https://picsum.photos/1920/300'
      />
      <section className='mt-10 mb-10'>
        {faqs.map((faq) => (
          <Accordion title={faq.title} body={faq.body} />
        ))}
      </section>
    </div>
  );
}

export default Faqs;
