export const adminFields = [
  {
    id: 'first_name',
    initialValue: '',
    placeholder: 'John',
    label: 'First name',
    validate: 'first_name',
    required: true,
    type: 'text',
  },
  {
    id: 'last_name',
    initialValue: '',
    placeholder: 'Doe',
    label: 'Last name',
    validate: 'last_name',
    required: true,
    type: 'text',
  },
  {
    id: 'email',
    initialValue: '',
    placeholder: 'youremail@domain.com',
    label: 'Email',
    validate: 'email',
    required: true,
    type: 'email',
  },
  // {
  //   id: 'phone',
  //   initialValue: '',
  //   placeholder: 'Celular',
  //   label: 'Celular',
  //   validate: 'phone',
  //   required: true,
  //   type: 'number',
  // },
];

export const adminFieldsOrg = [
  {
    id: 'razon_social',
    initialValue: '',
    placeholder: 'Razón Social',
    label: 'Razón Social',
    validate: 'razon_social',
    required: true,
    type: 'text',
  },
  {
    id: 'numero_documento',
    initialValue: '',
    placeholder: 'No. de Documento',
    label: 'No. de Documento',
    validate: 'numero_documento',
    required: true,
    type: 'text',
  },
  {
    id: 'nom_comercial',
    initialValue: '',
    placeholder: 'Nombre Comercial',
    label: 'Nombre Comercial',
    validate: 'nom_comercial',
    required: true,
    type: 'text',
  },
  {
    id: 'volumen_empresa',
    initialValue: '',
    placeholder: 'Tamaño de la empresa',
    label: 'Tamaño de la empresa',
    validate: 'volumen_empresa',
    required: true,
    type: 'text',
  },
  {
    id: 'industria',
    initialValue: '',
    placeholder: 'Industria',
    label: 'Industria',
    validate: 'industria',
    required: true,
    type: 'text',
  },
  {
    id: 'pais',
    initialValue: '',
    placeholder: 'País',
    label: 'País',
    validate: 'pais',
    required: true,
    type: 'text',
  },
  {
    id: 'web',
    initialValue: '',
    placeholder: 'Página Web',
    label: 'Página Web',
    validate: 'web',
    required: true,
    type: 'text',
  },
];

export const restorePasswordField = [
  {
    id: 'password',
    initialValue: '',
    placeholder: '********',
    label: 'Password *',
    validate: 'password',
    required: true,
    type: 'password',
  },
  {
    id: 'new_password',
    initialValue: '',
    placeholder: '********',
    label: 'Nueva Password *',
    validate: 'new_password',
    required: true,
    type: 'password',
  },
  {
    id: 'confirm_password',
    initialValue: '',
    placeholder: '********',
    label: 'Confirmar Password *',
    validate: 'confirm_password',
    required: true,
    type: 'password',
  },
];
