const agentLibraryConstants = {
  GET_AGENT_PAGE_REQUEST: 'GET_AGENT_PAGE_REQUEST',
  GET_AGENT_PAGE_SUCCESS: 'GET_AGENT_PAGE_SUCCESS',
  GET_AGENT_PAGE_FAILURE: 'GET_AGENT_PAGE_FAILURE',

  GET_ALL_AGENT_LIBRARY_REQUEST: 'GET_ALL_AGENT_LIBRARY_REQUEST',
  GET_ALL_AGENT_LIBRARY_SUCCESS: 'GET_ALL_AGENT_LIBRARY_SUCCESS',
  GET_ALL_AGENT_LIBRARY_FAILURE: 'GET_ALL_AGENT_LIBRARY_FAILURE',

  GET_AGENT_LIBRARY_BY_SLUG_REQUEST: 'GET_AGENT_LIBRARY_BY_SLUG_REQUEST',
  GET_AGENT_LIBRARY_BY_SLUG_SUCCESS: 'GET_AGENT_LIBRARY_BY_SLUG_SUCCESS',
  GET_AGENT_LIBRARY_BY_SLUG_FAILURE: 'GET_AGENT_LIBRARY_BY_SLUG_FAILURE',

  FILTER_ALL_AGENT_LIBRARY: 'FILTER_ALL_AGENT_LIBRARY',

  RESET_AGENT_LIBRARY: 'RESET_AGENT_LIBRARY',
};

export default agentLibraryConstants;
