const apimConstants = {
  GET_APIM_CONFIGS_REQUEST: 'GET_APIM_CONFIGS_REQUEST',
  GET_APIM_CONFIGS_SUCCESS: 'GET_APIM_CONFIGS_SUCCESS',
  GET_APIM_CONFIGS_FAILURE: 'GET_APIM_CONFIGS_FAILURE',

  GENERATE_CREDENTIALS_REQUEST: 'GENERATE_CREDENTIALS_REQUEST',
  GENERATE_CREDENTIALS_SUCCESS: 'GENERATE_CREDENTIALS_SUCCESS',
  GENERATE_CREDENTIALS_FAILURE: 'GENERATE_CREDENTIALS_FAILURE',
  RESET_GENERATED_CREDENTIALS: 'RESET_GENERATED_CREDENTIALS',

  ADD_SERVICES_REQUEST: 'ADD_SERVICES_REQUEST',
  ADD_SERVICES_SUCCESS: 'ADD_SERVICES_SUCCESS',
  ADD_SERVICES_FAILURE: 'ADD_SERVICES_FAILURE',
};

export default apimConstants;
