const apiManagerConstants = {
  GET_ALL_API_MANAGER_REQUEST: 'GET_ALL_API_MANAGER_REQUEST',
  GET_ALL_API_MANAGER_SUCCESS: 'GET_ALL_API_MANAGER_SUCCESS',
  GET_ALL_API_MANAGER_FAILURE: 'GET_ALL_API_MANAGER_FAILURE',
  GET_API_DETAIL_REQUEST: 'GET_API_DETAIL_REQUEST',
  GET_API_DETAIL_SUCCESS: 'GET_API_DETAIL_SUCCESS',
  GET_API_DETAIL_FAILURE: 'GET_API_DETAIL_FAILURE',
  RESET_API_DETAILED: 'RESET_API_DETAILED',
};

export default apiManagerConstants;