const BillingConstant = {
  GET_ALL_BILLING_REQUEST: 'GET_ALL_BILLING_REQUEST',
  GET_ALL_BILLING_SUCCESS: 'GET_ALL_BILLING_SUCCESS',
  GET_ALL_BILLING_FAILURE: 'GET_ALL_BILLING_FAILURE',

  FILTER_BILLINGS: 'FILTER_BILLINGS',

  GET_BILLING_REQUEST: 'GET_BILLING_REQUEST',
  GET_BILLING_SUCCESS: 'GET_BILLING_SUCCESS',
  GET_BILLING_FAILURE: 'GET_BILLING_FAILURE',

  GET_BILLING_DATA_ALL_REQUEST: 'GET_BILLING_DATA_ALL_REQUEST',
  GET_BILLING_DATA_ALL_SUCCESS: 'GET_BILLING_DATA_ALL_SUCCESS',
  GET_BILLING_DATA_ALL_FAILURE: 'GET_BILLING_DATA_ALL_FAILURE',

  RESET_BILLING: 'RESET_BILLING',
};

export default BillingConstant;
