const catalogConstants = {
  GET_ALL_CATALOG_REQUEST: 'GET_ALL_CATALOG_REQUEST',
  GET_ALL_CATALOG_SUCCESS: 'GET_ALL_CATALOG_SUCCESS',
  GET_ALL_CATALOG_FAILURE: 'GET_ALL_CATALOG_FAILURE',

  GET_CATALOG_SUCCESS: 'GET_CATALOG_SUCCESS',
  GET_CATALOG_FAILURE: 'GET_CATALOG_FAILURE',

  GET_ALL_CATALOG_PAGE_REQUEST: 'GET_ALL_CATALOG_PAGE_REQUEST',
  GET_ALL_CATALOG_PAGE_SUCCESS: 'GET_ALL_CATALOG_PAGE_SUCCESS',
  GET_ALL_CATALOG_PAGE_FAILURE: 'GET_ALL_CATALOG_PAGE_FAILURE',

  FILTER_ALL_CATALOG: 'FILTER_ALL_CATALOG',
  RESET_CATALOG: 'RESET_CATALOG',
}

export default catalogConstants;