const catalogConstants = {
  GET_ALL_CATALOG_REQUEST: 'GET_ALL_CATALOG_REQUEST',
  GET_ALL_CATALOG_SUCCESS: 'GET_ALL_CATALOG_SUCCESS',
  GET_ALL_CATALOG_FAILURE: 'GET_ALL_CATALOG_FAILURE',

  GET_CATALOG_SUCCESS: 'GET_CATALOG_SUCCESS',
  GET_CATALOG_FAILURE: 'GET_CATALOG_FAILURE',
}

export default catalogConstants;