const CodeSamplesConstant = {
  GET_ALL_CODE_SAMPLE_REQUEST: 'GET_ALL_CODE_SAMPLE_REQUEST',
  GET_ALL_CODE_SAMPLE_SUCCESS: 'GET_ALL_CODE_SAMPLE_SUCCESS',
  GET_ALL_CODE_SAMPLE_FAILURE: 'GET_ALL_CODE_SAMPLE_FAILURE',

  FILTER_CODE_SAMPLES: 'FILTER_CODE_SAMPLES',

  GET_CODE_SAMPLE_REQUEST: 'GET_CODE_SAMPLE_REQUEST',
  GET_CODE_SAMPLE_SUCCESS: 'GET_CODE_SAMPLE_SUCCESS',
  GET_CODE_SAMPLE_FAILURE: 'GET_CODE_SAMPLE_FAILURE',

  GET_CODE_SAMPLE_DATA_ALL_REQUEST: 'GET_CODE_SAMPLE_DATA_ALL_REQUEST',
  GET_CODE_SAMPLE_DATA_ALL_SUCCESS: 'GET_CODE_SAMPLE_DATA_ALL_SUCCESS',
  GET_CODE_SAMPLE_DATA_ALL_FAILURE: 'GET_CODE_SAMPLE_DATA_ALL_FAILURE',

  RESET_CODE_SAMPLE: 'RESET_CODE_SAMPLE',
};

export default CodeSamplesConstant;
