const groupConstants = {
  LIST_GROUPS_REQUEST: 'LIST_GROUPS_REQUEST',
  LIST_GROUPS_SUCCESS: 'LIST_GROUPS_SUCCESS',
  LIST_GROUPS_FAILURE: 'LIST_GROUPS_FAILURE',

  DELETE_GROUP_REQUEST: 'DELETE_GROUP_REQUEST',
  DELETE_GROUP_SUCCESS: 'DELETE_GROUP_SUCCESS',
  DELETE_GROUP_FAILURE: 'DELETE_GROUP_FAILURE',

  GET_GROUPS_USER_REQUEST: 'GET_GROUPS_USER_REQUEST',
  GET_GROUPS_USER_SUCCESS: 'GET_GROUPS_USER_SUCCESS',
  GET_GROUPS_USER_FAILURE: 'GET_GROUPS_USER_FAILURE',

  DELETE_GROUPS_USER_REQUEST: 'DELETE_GROUPS_USER_REQUEST',
  DELETE_GROUPS_USER_SUCCESS: 'DELETE_GROUPS_USER_SUCCESS',
  DELETE_GROUPS_USER_FAILURE: 'DELETE_GROUPS_USER_FAILURE',

  ADD_GROUPS_USER_REQUEST: 'ADD_GROUPS_USER_REQUEST',
  ADD_GROUPS_USER_SUCCESS: 'ADD_GROUPS_USER_SUCCESS',
  ADD_GROUPS_USER_FAILURE: 'ADD_GROUPS_USER_FAILURE',

};

export default groupConstants;
