const libraryConstants = {
  GET_ALL_LIBRARY_REQUEST: 'GET_ALL_LIBRARY_REQUEST',
  GET_ALL_LIBRARY_SUCCESS: 'GET_ALL_LIBRARY_SUCCESS',
  GET_ALL_LIBRARY_FAILURE: 'GET_ALL_LIBRARY_FAILURE',

  GET_LIBRARY_REQUEST: 'GET_LIBRARY_REQUEST',
  GET_LIBRARY_SUCCESS: 'GET_LIBRARY_SUCCESS',
  GET_LIBRARY_FAILURE: 'GET_LIBRARY_FAILURE',

  GET_APIS_REQUEST: 'GET_APIS_REQUEST',
  GET_APIS_SUCCESS: 'GET_APIS_SUCCESS',
  GET_APIS_FAILURE: 'GET_APIS_FAILURE',

  GET_API_REQUEST: 'GET_API_REQUEST',
  GET_API_SUCCESS: 'GET_API_SUCCESS',
  GET_API_FAILURE: 'GET_API_FAILURE',

  GET_API_OPENAPI_REQUEST: 'GET_API_OPENAPI_REQUEST',
  GET_API_OPENAPI_SUCCESS: 'GET_API_OPENAPI_SUCCESS',
  GET_API_OPENAPI_FAILURE: 'GET_API_OPENAPI_FAILURE',

  FILTER_ALL_LIBRARY: 'FILTER_ALL_LIBRARY',

  RESET_LIBRARY: 'RESET_LIBRARY',
};

export default libraryConstants;
