const libraryConstants = {
  GET_ALL_LIBRARY_REQUEST: 'GET_ALL_LIBRARY_REQUEST',
  GET_ALL_LIBRARY_SUCCESS: 'GET_ALL_LIBRARY_SUCCESS',
  GET_ALL_LIBRARY_FAILURE: 'GET_ALL_LIBRARY_FAILURE',

  GET_LIBRARY_REQUEST: 'GET_LIBRARY_REQUEST',
  GET_LIBRARY_SUCCESS: 'GET_LIBRARY_SUCCESS',
  GET_LIBRARY_FAILURE: 'GET_LIBRARY_FAILURE',

  RESET_LIBRARY: 'RESET_LIBRARY',
};

export default libraryConstants;
