const libraryConstants = {
  GET_ALL_MCP_LIBRARY_REQUEST: 'GET_ALL_MCP_LIBRARY_REQUEST',
  GET_ALL_MCP_LIBRARY_SUCCESS: 'GET_ALL_MCP_LIBRARY_SUCCESS',
  GET_ALL_MCP_LIBRARY_FAILURE: 'GET_ALL_MCP_LIBRARY_FAILURE',

  GET_MCP_LIBRARY_REQUEST: 'GET_MCP_LIBRARY_REQUEST',
  GET_MCP_LIBRARY_SUCCESS: 'GET_MCP_LIBRARY_SUCCESS',
  GET_MCP_LIBRARY_FAILURE: 'GET_MCP_LIBRARY_FAILURE',

  FILTER_ALL_MCP_LIBRARY: 'FILTER_ALL_MCP_LIBRARY',

  RESET_MCP_LIBRARY: 'RESET_MCP_LIBRARY',

  SELECTED_MCPS: 'SELECTED_MCPS',

};

export default libraryConstants;
