const libraryConstants = {
  GET_ALL_MCP_LIBRARY_REQUEST: 'GET_ALL_MCP_LIBRARY_REQUEST',
  GET_ALL_MCP_LIBRARY_SUCCESS: 'GET_ALL_MCP_LIBRARY_SUCCESS',
  GET_ALL_MCP_LIBRARY_FAILURE: 'GET_ALL_MCP_LIBRARY_FAILURE',

  GET_MCP_LIBRARY_REQUEST: 'GET_MCP_LIBRARY_REQUEST',
  GET_MCP_LIBRARY_SUCCESS: 'GET_MCP_LIBRARY_SUCCESS',
  GET_MCP_LIBRARY_FAILURE: 'GET_MCP_LIBRARY_FAILURE',

  GET_MCP_LIBRARY_BY_SLUG_REQUEST: 'GET_MCP_LIBRARY_BY_SLUG_REQUEST',
  GET_MCP_LIBRARY_BY_SLUG_SUCCESS: 'GET_MCP_LIBRARY_BY_SLUG_SUCCESS',
  GET_MCP_LIBRARY_BY_SLUG_FAILURE: 'GET_MCP_LIBRARY_BY_SLUG_FAILURE',

  CALL_TOOL_REQUEST: 'CALL_TOOL_REQUEST',
  CALL_TOOL_SUCCESS: 'CALL_TOOL_SUCCESS',
  CALL_TOOL_FAILURE: 'CALL_TOOL_FAILURE',

  FILTER_ALL_MCP_LIBRARY: 'FILTER_ALL_MCP_LIBRARY',

  RESET_MCP_LIBRARY: 'RESET_MCP_LIBRARY',

  SELECTED_MCPS: 'SELECTED_MCPS',

  SET_MCP_LIVE_SESSION: 'SET_MCP_LIVE_SESSION',

  CLEAR_MCP_LIVE_SESSION: 'CLEAR_MCP_LIVE_SESSION',

};

export default libraryConstants;
