const productsConstants = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

  GET_PRODUCTS_SKIP: 'GET_PRODUCTS_SKIP',

  GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

  RESET_PRODUCT: 'RESET_PRODUCT',

  GET_PRODUCT_SUSCRIPCION_REQUEST: 'GET_PRODUCT_SUSCRIPCION_REQUEST',
  GET_PRODUCT_SUSCRIPCION_SUCCESS: 'GET_PRODUCT_SUSCRIPCION_SUCCESS',
  GET_PRODUCT_SUSCRIPCION_FAILURE: 'GET_PRODUCT_SUSCRIPCION_FAILURE',

  GET_PRODUCT_API_REQUEST: 'GET_PRODUCT_API_REQUEST',
  GET_PRODUCT_API_SUCCESS: 'GET_PRODUCT_API_SUCCESS',
  GET_PRODUCT_API_FAILURE: 'GET_PRODUCT_API_FAILURE',

  GET_PRODUCT_API_SKIP: 'GET_PRODUCT_API_SKIP',

  GET_SUBSCRIPTIONS_REQUEST: 'GET_SUBSCRIPTIONS_REQUEST',
  GET_SUBSCRIPTIONS_SUCCESS: 'GET_SUBSCRIPTIONS_SUCCESS',
  GET_SUBSCRIPTIONS_FAILURE: 'GET_SUBSCRIPTIONS_FAILURE',

  GET_MY_PRODUCTS_REQUEST: 'GET_MY_PRODUCTS_REQUEST',
  GET_MY_PRODUCTS_SUCCESS: 'GET_MY_PRODUCTS_SUCCESS',
  GET_MY_PRODUCTS_FAILURE: 'GET_MY_PRODUCTS_FAILURE',

  CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',

  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  RESET_UPDATE_PRODUCT: 'RESET_UPDATE_PRODUCT',

  REMOVE_API_FROM_PRODUCT_REQUEST: 'REMOVE_API_FROM_PRODUCT_REQUEST',
  REMOVE_API_FROM_PRODUCT_SUCCESS: 'REMOVE_API_FROM_PRODUCT_SUCCESS',
  REMOVE_API_FROM_PRODUCT_FAILURE: 'REMOVE_API_FROM_PRODUCT_FAILURE',
  RESET_REMOVE_API_FROM_PRODUCT: 'RESET_REMOVE_API_FROM_PRODUCT',

  ADD_API_TO_PRODUCT_REQUEST: 'ADD_API_TO_PRODUCT_REQUEST',
  ADD_API_TO_PRODUCT_SUCCESS: 'ADD_API_TO_PRODUCT_SUCCESS',
  ADD_API_TO_PRODUCT_FAILURE: 'ADD_API_TO_PRODUCT_FAILURE',
  RESET_ADD_API_TO_PRODUCT: 'RESET_ADD_API_TO_PRODUCT',
};

export default productsConstants;
