const settingPageConstants = {
  GET_ALL_SETTING_PAGE_REQUEST: 'GET_ALL_SETTING_PAGE_REQUEST',
  GET_ALL_SETTING_PAGE_SUCCESS: 'GET_ALL_SETTING_PAGE_SUCCESS',
  GET_ALL_SETTING_PAGE_FAILURE: 'GET_ALL_SETTING_PAGE_FAILURE',

  FILTER_SETTING_PAGES: 'FILTER_SETTING_PAGES',

  GET_SETTING_PAGE_REQUEST: 'GET_SETTING_PAGE_REQUEST',
  GET_SETTING_PAGE_SUCCESS: 'GET_SETTING_PAGE_SUCCESS',
  GET_SETTING_PAGE_FAILURE: 'GET_SETTING_PAGE_FAILURE',

  GET_SETTING_PAGE_DATA_ALL_REQUEST: 'GET_SETTING_PAGE_DATA_ALL_REQUEST',
  GET_SETTING_PAGE_DATA_ALL_SUCCESS: 'GET_SETTING_PAGE_DATA_ALL_SUCCESS',
  GET_SETTING_PAGE_DATA_ALL_FAILURE: 'GET_SETTING_PAGE_DATA_ALL_FAILURE',

  RESET_SETTING_PAGE: 'RESET_SETTING_PAGE',
};

export default settingPageConstants;
