const userCredentialConstants = {
  GET_USER_CREDENTIALS_REQUEST: 'USER_CREDENTIAL/GET_REQUEST',
  GET_USER_CREDENTIALS_SUCCESS: 'USER_CREDENTIAL/GET_SUCCESS',
  GET_USER_CREDENTIALS_FAILURE: 'USER_CREDENTIAL/GET_FAILURE',

  GET_USER_CREDENTIAL_REQUEST: 'USER_CREDENTIAL/GET_ONE_REQUEST',
  GET_USER_CREDENTIAL_SUCCESS: 'USER_CREDENTIAL/GET_ONE_SUCCESS',
  GET_USER_CREDENTIAL_FAILURE: 'USER_CREDENTIAL/GET_ONE_FAILURE',

  CREATE_USER_CREDENTIAL_REQUEST: 'USER_CREDENTIAL/CREATE_REQUEST',
  CREATE_USER_CREDENTIAL_SUCCESS: 'USER_CREDENTIAL/CREATE_SUCCESS',
  CREATE_USER_CREDENTIAL_FAILURE: 'USER_CREDENTIAL/CREATE_FAILURE',

  ADD_PRODUCTS_REQUEST: 'USER_CREDENTIAL/ADD_PRODUCTS_REQUEST',
  ADD_PRODUCTS_SUCCESS: 'USER_CREDENTIAL/ADD_PRODUCTS_SUCCESS',
  ADD_PRODUCTS_FAILURE: 'USER_CREDENTIAL/ADD_PRODUCTS_FAILURE',
  RESET_ADD_PRODUCTS: 'USER_CREDENTIAL/RESET_ADD_PRODUCTS',
};

export default userCredentialConstants;
