const userCredentialConstants = {
  GET_USER_CREDENTIALS_REQUEST: 'USER_CREDENTIAL/GET_REQUEST',
  GET_USER_CREDENTIALS_SUCCESS: 'USER_CREDENTIAL/GET_SUCCESS',
  GET_USER_CREDENTIALS_FAILURE: 'USER_CREDENTIAL/GET_FAILURE',

  CREATE_USER_CREDENTIAL_REQUEST: 'USER_CREDENTIAL/CREATE_REQUEST',
  CREATE_USER_CREDENTIAL_SUCCESS: 'USER_CREDENTIAL/CREATE_SUCCESS',
  CREATE_USER_CREDENTIAL_FAILURE: 'USER_CREDENTIAL/CREATE_FAILURE',
};

export default userCredentialConstants;
