const usersConstants = {
  LIST_USERS_REQUEST: 'LIST_USERS_REQUEST',
  LIST_USERS_SUCCESS: 'LIST_USERS_SUCCESS',
  LIST_USERS_FAILURE: 'LIST_USERS_FAILURE',

  GET_USERS_DETAIL_REQUEST: 'GET_USERS_DETAIL_REQUEST',
  GET_USERS_DETAIL_SUCCESS: 'GET_USERS_DETAIL_SUCCESS',
  GET_USERS_DETAIL_FAILURE: 'GET_USERS_DETAIL_FAILURE',

  UPDATE_USERS_STATUS_REQUEST: 'UPDATE_USERS_STATUS_REQUEST',
  UPDATE_USERS_STATUS_SUCCESS: 'UPDATE_USERS_STATUS_SUCCESS',
  UPDATE_USERS_STATUS_FAILURE: 'UPDATE_USERS_STATUS_FAILURE',

};

export default usersConstants;
