apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $ACR_IMAGE
          ports:
            - containerPort: $APP_PORT
              name: $APP_PORT_NAME
          env:
            - name: REACT_APP_STRAPI_URL
              value: "$REACT_APP_STRAPI_URL"
            - name: REACT_APP_SURA_URL
              value: "$REACT_APP_SURA_URL"
            - name: REACT_APP_SUBSCRIPTION_ID
              value: "$REACT_APP_SUBSCRIPTION_ID"
            - name: REACT_APP_RESOURCE_GROUP_NAME
              value: "$REACT_APP_RESOURCE_GROUP_NAME"
            - name: REACT_APP_SERVICE_NAME
              value: "$REACT_APP_SERVICE_NAME"
            - name: REACT_APP_API_VERSION
              value: "$REACT_APP_API_VERSION"
            - name: REACT_APP_REMEMBER_KEY
              value: "$REACT_APP_REMEMBER_KEY"
            - name: REACT_APP_PRIMARY_KEY
              value: "$REACT_APP_PRIMARY_KEY"
            - name: REACT_APP_APIM_UID
              value: "$REACT_APP_APIM_UID"
            - name: REACT_APP_TOKEN_VALID_DAYS
              value: "$REACT_APP_TOKEN_VALID_DAYS"
            - name: REACT_APP_LIST_API_TOP
              value: "$REACT_APP_LIST_API_TOP"
            - name: REACT_APP_LIST_PRODUCT_APIS_TOP
              value: "$REACT_APP_LIST_PRODUCT_APIS_TOP"
            - name: REACT_APP_LIST_PRODUCT_TOP
              value: "$REACT_APP_LIST_PRODUCT_TOP"
            - name: REACT_APP_LIST_SUBSCRIPTIONS
              value: "$REACT_APP_LIST_SUBSCRIPTIONS"
            - name: WDS_SOCKET_PORT
              value: "$WDS_SOCKET_PORT"
            - name: REACT_APP_HOME_PAGE_SLUG
              value: "$REACT_APP_HOME_PAGE_SLUG"
            - name: REACT_APP_BLOG_PAGE_SLUG
              value: "$REACT_APP_BLOG_PAGE_SLUG"
            - name: REACT_APP_FAQ_PAGE_SLUG
              value: "$REACT_APP_FAQ_PAGE_SLUG"
            - name: REACT_APP_APIS_PAGE_SLUG
              value: "$REACT_APP_APIS_PAGE_SLUG"
            - name: REACT_APP_EMAIL_ENDPOINT
              value: "$REACT_APP_EMAIL_ENDPOINT"
            - name: REACT_APP_API_KEY_SEND_GRID
              value: "$REACT_APP_API_KEY_SEND_GRID"
            - name: REACT_APP_EMAIL_SUBSCRIPTION_KEY
              value: "$REACT_APP_EMAIL_SUBSCRIPTION_KEY"
            - name: REACT_APP_EMAIL_FROM
              value: "$REACT_APP_EMAIL_FROM"
            - name: REACT_APP_EMAIL_CONVERSATION_TEMPLATE_ID
              value: "$REACT_APP_EMAIL_CONVERSATION_TEMPLATE_ID"
            - name: REACT_APP_EMAIL_CONTACT_TEMPLATE_ID
              value: "$REACT_APP_EMAIL_CONTACT_TEMPLATE_ID"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      imagePullpolicy: Always
      imagePullSecrets:
        - name: $ACR_SECRET_IMAGE_PULL

---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
    - name: ${APP_PORT_NAME}-svc
      nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: $APP_PORT_NAME

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: $APP_NAME
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  host: $HTTP_HOST
  port:
    targetPort: ${APP_PORT_NAME}-svc
  to:
    kind: Service
    name: $APP_NAME
  tls:
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIGRjCCBS6gAwIBAgIRANTp/pJaNE3TE7711xO2eV8wDQYJKoZIhvcNAQELBQAw
      gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
      BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
      AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
      QTAeFw0yMTEwMTgwMDAwMDBaFw0yMjExMTgyMzU5NTlaMB8xHTAbBgNVBAMMFCou
      c2VndXJvc3N1cmEuY29tLm14MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAwa+q9h4Yc8F+Hsw/QKVKCprtoy2B2rZlKm7Ky8Cp+2nHkMIFo5eR+RwzX9pN
      rBfG4CuR+zXIz/BD7Y/ADvs4xdfkiafLAHi/vy6OCvHE/3ZXUyA6Weca9lqqQyqj
      IIZKKLp61aV1fIss/+Q91y5HDgV63+Si0ix0uUiMFE7mFvoNYFb9SJMxc8cdJ4sW
      rJXX6gknyJ2qwqu2//c1Q6W4RGkWn3KBKFcuKZpk1X17QABiqohWBZ7RaC6coQOW
      HNk7wqryCNXxBIXyMpExiLGSoSwpTmILstilQO2qmmeZAPwAjJAd+YBfpaQBeGSS
      hA1YForFBj6dEpjeT3x27hGgMQIDAQABo4IDCjCCAwYwHwYDVR0jBBgwFoAUjYxe
      xFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFLOmbmHIhkgXgzlM/9htjfhsbmsO
      MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUF
      BwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYB
      BQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYB
      BQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1Nl
      Y3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsG
      AQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTAzBgNVHREELDAqghQqLnNl
      Z3Vyb3NzdXJhLmNvbS5teIISc2VndXJvc3N1cmEuY29tLm14MIIBfgYKKwYBBAHW
      eQIEAgSCAW4EggFqAWgAdQBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5t
      RwAAAXyTj6P9AAAEAwBGMEQCIHazCWiV9I1pKdTVKe3ZJnE/cy/O1tHYFuTxSsNv
      8ETXAiAZ/Ndr+agOIiue2GuDcdY/dfSE1q+WRbRW9M0R81ofagB3AEHIyrHfIkZK
      EMahOglCh15OMYsbA+vrS8do8JBilgb2AAABfJOPo8YAAAQDAEgwRgIhAOUBXFss
      cB0ZEzLCdhQ0dI0AFkWxJ1e5kEG3AfikL8w5AiEAiNyS/tLcBj2niDG83q8J+K/4
      jVeWqLPhwhOX3EEsvQgAdgApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3H
      hAAAAXyTj6OTAAAEAwBHMEUCIQD6cEJ4+UH9SeriAmLr0DDsmkOh9yKW0WZ81i4K
      uYK7CQIgE7Z4usQBDu129zrWyrl3rHbf3WN0lHjcQ2dGWkRtbvgwDQYJKoZIhvcN
      AQELBQADggEBAASjsdE3FVASboIvlj/4jybnATdpqgLuBwqGUQCLQ8gyb3Ny1S7Q
      e47bFN8qIQDrizTpWwlKlrMarMPhjGccbkKZFIG2D47y4DLNYJEK+w1w7KZTE3e1
      VkrkJ5o759kH9v5YeyolOCxce2zWQjMV8xQEV71opFPtXfg3MyDECT0gaZz0Z9M6
      lmpbVSAoKa3tmaq89GMxyDP7oiIU+d++7UUq1FJ50a4oZFEJFBC+Dxz/4usMVJZE
      FS3EOp68R8MP+mA/Ug57bOvOQ7YCU77lgpQnaiZHQzAEdcZiMesRKpadZ7dfZXzu
      5/eMGtOUPhw9zPiJREnFOCgqzAVojD/sQ3k=
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDBr6r2HhhzwX4e
      zD9ApUoKmu2jLYHatmUqbsrLwKn7aceQwgWjl5H5HDNf2k2sF8bgK5H7NcjP8EPt
      j8AO+zjF1+SJp8sAeL+/Lo4K8cT/dldTIDpZ5xr2WqpDKqMghkoounrVpXV8iyz/
      5D3XLkcOBXrf5KLSLHS5SIwUTuYW+g1gVv1IkzFzxx0nixasldfqCSfInarCq7b/
      9zVDpbhEaRafcoEoVy4pmmTVfXtAAGKqiFYFntFoLpyhA5Yc2TvCqvII1fEEhfIy
      kTGIsZKhLClOYguy2KVA7aqaZ5kA/ACMkB35gF+lpAF4ZJKEDVgWisUGPp0SmN5P
      fHbuEaAxAgMBAAECggEBAJ9Hnplt4H/5RIWBRBcelsgn5ntF5j79ti5yFFYBKAi4
      UcSqukZxVDr/RQRzm2KF3yfkzNVAwta16LbJe5EWafbRd4D4uwm1Q0Kuv2MitfW7
      1U5n93SNiG/F2bUIsEQEC6J40KE3w2lbbvM1OOHnjclrGkRbWsbqhkcE8SWWSMPl
      Ci9IzJOM4d/vHZAbHNvp0WIVLXC7lhxzfPrwU+e7QieqZnFV45CF4artMxbBGbsT
      KiNIEZcHUKb5w8vzzoJprcovJ8R8M+FE6DIRiixNCIaIhjr76PeaDmkJd/aKTKcH
      2rnrsHCkLbaaxdjoL7wrUXgiVCwAaVn5LLBEPTqwvr0CgYEA6s0b+6iNHYkWLnAD
      hCQvX7nk/3DFvFF2tOvhOOQ8drM3+0m7fMN/abv7cJyS2pnBSFf62igBlBihXM/6
      ul255UwsDiCYKOBmb3ARWy9HMxa8TuBeOYDD6FBcoIejQu3d5+dHg6nx4Bb/RZIx
      FxXC0ZJkzswwfoZetSlK3N3XmN8CgYEA0yxHkhlGM1HZ50cDf9xLv9xlgCMrvaGb
      QkIUFPLkdPF52O+nw/Vh7JmEHdZL7bKsRUFhagdwLsd48bgBDU6JnhVrr7OwD0xb
      PVHpc677ChEmmagaCqzYE3cAQCRqpqgOMJO8NyrtN0N6QLcAG6yiYftjTmsD4G9r
      u6ykZtIrGO8CgYEAvddwlJzG2+aG5Kz0atbG5uLqYA3SElzbWZSN2O3QZTiqPqZy
      zIFUdyziMz6lDdHbEJ7x14kZHaB8dwpBcoVtVBOuWw3HeOVWbStzHQKw0oHDZxLJ
      nDycKS0wdyqzud2Q2XuJus6hHcn6Q0ncHwodJkzy7LDzVJlX4amtOb60HokCgYAs
      sRxckTjIN7R0PBVDhC4L5uscWVUyhvdC6JUzccxj648sGFxbHp2g40SQw//ByKSo
      65NgSz60x8aS8axXUp3RdRsbTl4efrx4l9NehlPe545Ryr/oLnh0diT5bjucFckb
      Ask8q7sUjRVciN5e/QRI1FlKCWACqdIVIA6TLDuuxQKBgQDgTkbdUkOoCEnkrJOT
      trD9i1BAo+CpmRxcdrOUb9aJqbK5xpk1jyLG787wZDYL1V5DT3IwleFDB8jTVrBj
      FHopsoQvSfKhotDCUWNaNope6fWmR8GTdP1qrxXWHww4ABuK241Twreo2I62W/xL
      vmai8Shh2350PcUby8Qvbu8pcA==
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7
      MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD
      VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE
      AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4
      MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
      MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
      ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
      aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI
      s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG
      vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ
      Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb
      IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0
      tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E
      xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV
      icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5
      D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ
      WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ
      5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG
      KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg
      EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID
      ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG
      BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t
      L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr
      BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA
      A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+
      rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+
      /czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA
      CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F
      zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA
      vGp4z7h/jnZymQyd/teRCBaho1+V
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
      iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
      cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
      BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
      MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
      BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
      ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
      VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
      TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
      eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
      oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
      Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
      uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
      BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
      +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
      A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
      CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
      LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
      BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
      bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
      L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
      ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
      7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
      H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
      RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
      xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
      sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
      l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
      6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
      LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
      yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
      00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEMjCCAxqgAwIBAgIBATANBgkqhkiG9w0BAQUFADB7MQswCQYDVQQGEwJHQjEb
      MBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRow
      GAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmlj
      YXRlIFNlcnZpY2VzMB4XDTA0MDEwMTAwMDAwMFoXDTI4MTIzMTIzNTk1OVowezEL
      MAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
      BwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMM
      GEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEP
      ADCCAQoCggEBAL5AnfRu4ep2hxxNRUSOvkbIgwadwSr+GB+O5AL686tdUIoWMQua
      BtDFcCLNSS1UY8y2bmhGC1Pqy0wkwLxyTurxFa70VJoSCsN6sjNg4tqJVfMiWPPe
      3M/vg4aijJRPn2jymJBGhCfHdr/jzDUsi14HZGWCwEiwqJH5YZ92IFCokcdmtet4
      YgNW8IoaE+oxox6gmf049vYnMlhvB/VruPsUK6+3qszWY19zjNoFmag4qMsXeDZR
      rOme9Hg6jc8P2ULimAyrL58OAd7vn5lJ8S3frHRNG5i1R8XlKdH5kBjHYpy+g8cm
      ez6KJcfA3Z3mNWgQIJ2P2N7Sw4ScDV7oL8kCAwEAAaOBwDCBvTAdBgNVHQ4EFgQU
      oBEKIz6W8Qfs4q8p74Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
      MAMBAf8wewYDVR0fBHQwcjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5jb20v
      QUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNqA0oDKGMGh0dHA6Ly9jcmwuY29t
      b2RvLm5ldC9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDANBgkqhkiG9w0BAQUF
      AAOCAQEACFb8AvCb6P+k+tZ7xkSAzk/ExfYAWMymtrwUSWgEdujm7l3sAg9g1o1Q
      GE8mTgHj5rCl7r+8dFRBv/38ErjHT1r0iWAFf2C3BUrz9vHCv8S5dIa2LX1rzNLz
      Rt0vxuBqw8M0Ayx9lt1awg6nCpnBBYurDC/zXDrPbDdVCYfeU0BsWO/8tqtlbgT2
      G9w84FoVxp7Z8VlIMCFlA2zs6SFz7JsDoeA3raAVGI/6ugLOpyypEBMs1OUIJqsi
      l2D4kF501KKaU73yqWjgom7C12yxow+ev+to51byrvLjKzg6CYG1a4XXvi3tPxq3
      smPi9WIsgtRqAEFQ8TmDn5XpNpaYbg==
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
