export const fieldsAppSandbox = [
  {
    id: 'clientId',
    initialValue: 'ClienteID',
    placeholder: 'Client ID',
    label: 'Client ID',
    validate: 'clientId',
    required: false,
    type: 'password',
    disabled: true,
  },
  {
    id: 'clientSecret',
    initialValue: 'ClientSecret',
    placeholder: 'Client Secret',
    label: 'Client Secret',
    validate: 'clientSecret',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
  {
    id: 'host',
    initialValue: 'ClientSecret',
    placeholder: 'Host',
    label: 'Host',
    validate: 'host',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
];

export const fieldsAppPre = [
  {
    id: 'clientIdPre',
    initialValue: 'ClienteIDPRE',
    placeholder: 'Client ID',
    validate: 'clientId',
    required: true,
    type: 'password',
    disabled: false,
  },
  {
    id: 'clientSecretPre',
    initialValue: 'ClientSecretPRE',
    placeholder: 'Client Secret',
    validate: 'clientSecret',
    required: true,
    type: 'password',
    iconName: 'MdOutlineRemoveRedEye',
    disabled: false,
  },
  {
    id: 'hostPre',
    initialValue: 'ClientSecretPRE',
    placeholder: 'Host',
    validate: 'host',
    required: true,
    type: 'password',
    iconName: 'MdOutlineRemoveRedEye',
    disabled: false,
  },
];
