export const fieldsAppSandbox = [
  {
    id: 'clientId',
    initialValue: '',
    placeholder: 'Client ID',
    label: 'Client ID',
    validate: 'clientId',
    required: false,
    type: 'password',
    disabled: true,
  },
  {
    id: 'clientSecret',
    initialValue: '',
    placeholder: 'Client Secret',
    label: 'Client Secret',
    validate: 'clientSecret',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
  {
    id: 'host',
    initialValue: '',
    placeholder: 'Host',
    label: 'Host',
    validate: 'host',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
];

export const fieldsAppPre = [
  {
    id: 'clientId',
    initialValue: '',
    placeholder: 'Client ID',
    validate: 'clientId',
    required: true,
    type: 'password',
    disabled: false,
  },
  {
    id: 'clientSecret',
    initialValue: '',
    placeholder: 'Client Secret',
    validate: 'clientSecret',
    required: true,
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: false,
  },
  {
    id: 'host',
    initialValue: '',
    placeholder: 'Host',
    validate: 'host',
    required: true,
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: false,
  },
];
