export const fieldsAppSandbox = [
  {
    id: 'clientId',
    initialValue: 'ClienteID',
    placeholder: 'Client ID',
    label: 'Client ID',
    validate: 'clientId',
    required: false,
    type: 'password',
    disabled: true,
  },
  {
    id: 'clientSecret',
    initialValue: 'ClientSecret',
    placeholder: 'Client Secret',
    label: 'Client Secret',
    validate: 'clientSecret',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
  {
    id: 'host',
    initialValue: 'ClientHost',
    placeholder: 'Host',
    label: 'Host',
    validate: 'host',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
];

export const fieldsAppPre = [
  {
    id: 'clientIdPre',
    initialValue: 'ClienteIDPre',
    placeholder: 'Client ID Pre',
    label: 'Client ID Pre',
    validate: 'clientIdPre',
    required: false,
    type: 'password',
    disabled: true,
  },
  {
    id: 'clientSecretPre',
    initialValue: 'ClientSecretPre',
    placeholder: 'Client SecretPre',
    label: 'Client Secret Pre',
    validate: 'clientSecretPre',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
  {
    id: 'hostPre',
    initialValue: 'ClientHostPre',
    placeholder: 'Host PRE',
    label: 'Host PRE',
    validate: 'hostPre',
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
    disabled: true,
  },
];
