export const fieldsRegister = [
  {
    id: 'first_name',
    initialValue: '',
    placeholder: 'John',
    label: 'First name',
    validate: 'first_name',
    required: true,
    type: 'text',
  },
  {
    id: 'last_name',
    initialValue: '',
    placeholder: 'Doe',
    label: 'Last name',
    validate: 'last_name',
    required: true,
    type: 'text',
  },
  // {
  //   id: 'phone',
  //   initialValue: '',
  //   placeholder: 'Celular',
  //   label: 'Celular',
  //   validate: 'phone',
  //   required: true,
  //   type: 'number',
  // },
  // {
  //   id: 'company',
  //   initialValue: '',
  //   placeholder: 'Compañia',
  //   label: 'Compañia',
  //   validate: 'company',
  //   required: true,
  //   type: 'text',
  // },
  // {
  //   id: 'industry',
  //   initialValue: '',
  //   placeholder: 'Industria',
  //   label: 'Industria',
  //   validate: 'industry',
  //   required: true,
  //   type: 'email',
  // },
  {
    id: 'email',
    initialValue: '',
    placeholder: 'youremail@domain.com',
    label: 'Email',
    validate: 'email',
    required: true,
    type: 'email',
  },
  {
    id: 'password',
    initialValue: '',
    placeholder: '********',
    label: 'Password',
    validate: 'password',
    required: true,
    type: 'password',
  },
  {
    id: 'password_confirmation',
    initialValue: '',
    placeholder: '********',
    label: 'Confirmar password',
    validate: 'password_confirmation',
    required: true,
    type: 'password',
  },
];

export const fieldsLogin = [
  {
    id: 'email',
    initialValue: '',
    placeholder: 'Email',
    validate: 'email',
    required: true,
    type: 'email',
  },
  {
    id: 'password',
    initialValue: '',
    placeholder: 'Password',
    validate: 'password',
    required: true,
    type: 'password',
    icon: true,
    iconName: 'MdOutlineRemoveRedEye',
  },
];
export const fieldsContact = [
  {
    id: 'email',
    initialValue: '',
    placeholder: 'Email',
    validate: 'email',
    required: true,
    type: 'email',
  },
  {
    id: 'name',
    initialValue: '',
    placeholder: 'Name',
    validate: 'name',
    required: true,
    type: 'text',
  },
];
export const fieldsContactExtend = [
  {
    id: 'first_name',
    initialValue: '',
    placeholder: 'Nombre',
    label: 'Nombre',
    validate: 'first_name',
    required: true,
    type: 'text',
  },
  {
    id: 'last_name',
    initialValue: '',
    placeholder: 'Apellido',
    label: 'Apellido',
    validate: 'last_name',
    required: true,
    type: 'text',
  },
  {
    id: 'email',
    initialValue: '',
    placeholder: 'Email',
    label: 'Email',
    validate: 'email',
    required: true,
    type: 'email',
  },
  {
    id: 'phone',
    initialValue: '',
    placeholder: 'Celular',
    label: 'Celular',
    validate: 'phone',
    required: true,
    type: 'number',
  },
  {
    id: 'topics',
    initialValue: '',
    placeholder: 'Temas',
    label: 'Temas',
    validate: 'topics',
    required: true,
    type: 'text',
  },
  {
    id: 'subject',
    initialValue: '',
    placeholder: 'Asunto',
    label: 'Asunto',
    validate: 'subject',
    required: true,
    type: 'text',
  },
  {
    id: 'message',
    initialValue: '',
    placeholder: 'Mensaje',
    label: 'Mensaje',
    validate: 'message',
    required: true,
    type: 'textarea',
  },
];
